export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 125,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'https://www.simplyrecipes.com/thmb/pjYMLcsKHkr8D8tYixmaFNxppPw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__09__easy-pepperoni-pizza-lead-3-8f256746d649404baa36a44d271329bc.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Meatball',
      price: 120,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: 'https://static01.nyt.com/images/2015/09/23/dining/23RECIPE5/23RECIPE5-superJumbo-v2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 156,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'https://insanelygoodrecipes.com/wp-content/uploads/2020/10/Hamburger-with-Sesame-Seeds-Cheese-and-Veggies.png',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id: '4',
      name: 'Fried Potatoes',
      price: 80,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2004/2/25/0/bw2b07_french_fries1.jpg.rend.hgtvcom.616.462.suffix/1383933925968.jpeg',
      tags: ['FastFood', 'Fry'],
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 110,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'https://www.seriouseats.com/thmb/2nouHHsjM0bN1vwXMOZGUkLFsJ8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2017__12__20171115-chicken-soup-vicky-wasik-11-80db1a04d84a43a089e0559efdddd517.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '6',
      name: 'Vegetables Pizza',
      price: 190,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'https://i0.wp.com/www.thursdaynightpizza.com/wp-content/uploads/2022/06/veggie-pizza-side-view-out-of-oven.png?resize=720%2C480&ssl=1',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
  ];
  
  export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ];
  
  export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];